### ISSUE TITLE
The command cargo run -r --example db throws an error when processing images with complex structures.

### ISSUE THREAD

**Issue by faith0831** [jamjamjon/usls#34] opened 2024-09-02 03:06 UTC
The following is the error message:

✅ Backend: ONNXRuntime | OpSet: 11 | EP: Cpu(0) | DType: [Float32] | Params: 0 B
✅ Dryrun x5
✅ Annotated image saved to: runs\DB\2024-09-02-11-00-04-620791900.png
thread 'main' panicked at xxxx\imageproc-0.24.0\src\drawing\polygon.rs:36:9:
First point Point { x: 258, y: 99 } == last point Point { x: 258, y: 99 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\examples\db.exe` (exit code: 101)

This is the image used during testing:

![db2](https://github.com/user-attachments/assets/c9be633d-6d40-406e-a5aa-57a2651036af)

**Comment by jamjamjon** [comment] 2024-09-02 15:52
This is due to a bug in the imageproc library when drawing polygons caused by the conversion from `f64` to `i32`. The issue has been fixed in version `0.0.13`. 

Below is the inference result. Thank you very much for discovering this bug.

![2024-09-02-23-28-58-522548583](https://github.com/user-attachments/assets/a0b093b5-4ef6-4c5a-8273-e8c7d5e04ce8)

**Comment by faith0831** [comment] 2024-09-03 04:59
good job!!

**Closed** 2024-09-03 11:03 UTC
